version: 0.0
os: linux
files:
  - source: /appspec.yml
    destination: /home/ec2-user/cladder/
hooks:
  BeforeInstall:
    - location: ./startscript.sh
  AfterInstall:
    - location: ./startscript.sh
      timeout: 180
  ApplicationStart:
    - location: ./startscript.sh
      timeout: 3600
  ValidateService:
    - location: Scripts/MonitorService.sh
      timeout: 3600
      runas: codedeployuser
