version: 0.0
os: linux
files:
   - source: build/*
   - destination: /home/ec2-user/cladder
hooks:
  BeforeInstall:
    - location: stopscript.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: deletescript.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: startscript.sh
      timeout: 3600
      runas: root
