version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/Ca-Lad/
permissions:
- object: /
   pattern: "**"
   owner: ec2-user
   group: ec2-user
hooks:
ApplicationStop:
- location: /bin/node/app-stop
  timeout: 10
  runas: ec2-user
   
  
