version: 0.0
os: linux
files:
  - source: /appspec.yml
    destination: /home/ec2-user/cladder/
hooks:
  BeforeInstall:
    - location: ./stopscript.sh
  AfterInstall:
    - location: ./deletescript.sh
      timeout: 180
  ApplicationStart:
    - location: ./startscript.sh
      timeout: 3600
      runas: root
