# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
     # - echo Installing Mocha...
     # - npm install -g mocha      
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - npm run build
      # - npm start     
  # Include only the files required for your application to run.
  post_build:
    commands:
       - echo Build completed on `date`
       - echo Script executed from `pwd`        
artifacts:
  files:
    - src/appspec.yml
    - appspec.yml
    - '**/*'
  base-directory: build
  # files:
    # - src/index.js
    # - src/App.js
   # - src/index.js
   # - src/appspec.yaml
    # - package.json
    # - node_modules/**/*
     # - '**/*'
     # - appspec.yml
     # - '**/build'
     # - '**/*.sh'
    # - base-directory:build
    
    

